### ISSUE TITLE
No pangea-electron dir created and no release script included in 2.12.6 on Mac

### ISSUE THREAD

**Issue by andytudhope** [Bit-Nation/pangea-electron#1]
The commands I ran on Mac OSX:

```
git clone https://github.com/Bit-Nation/pangea.git
cd pangea
nvm install 5
     v5.12.0 is already installed.
     Now using node v5.12.0 (npm v3.8.6)
npm install
     npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
     npm WARN prefer global marked@0.3.6 should be installed with -g
     npm WARN prefer global ssb-marked@0.5.4 should be installed with -g
     npm WARN prefer global node-ninja@1.0.2 should be installed with -g
     npm WARN prefer global node-gyp@3.4.0 should be installed with -g
```
then everything installed fine as far as I can tell, followed by these two warnings:

```
     npm WARN optional Skipping failed optional dependency /dbus-native/abstract-socket:
     npm WARN notsup Not compatible with your operating system or architecture: abstract-socket@1.1.0
```
NPM link seemed to work OK:
```
> pangea@2.12.6 prepublish /Users/devmac/bitnation/pangea
> npm run build-release


> pangea@2.12.6 build-release /Users/devmac/bitnation/pangea
> npm run build-release:js


> pangea@2.12.6 build-release:js /Users/devmac/bitnation/pangea
> cross-env NODE_ENV=production browserify ./ui/main.js --extension=.jsx -o ./ui/main.build.js

npm WARN optional Skipping failed optional dependency /dbus-native/abstract-socket:
npm WARN notsup Not compatible with your operating system or architecture: abstract-socket@1.1.0
/Users/devmac/.nvm/versions/node/v5.12.0/bin/pangea -> /Users/devmac/.nvm/versions/node/v5.12.0/lib/node_modules/pangea/index.js
/Users/devmac/.nvm/versions/node/v5.12.0/lib/node_modules/pangea -> /Users/devmac/bitnation/pangea
```
But then there is no `~/pangea-electron/app` directory and no release script? Also checked for a `~/.pangea-electron/app` directory and found nothing. Not sure where to go from here.

```
~/bitnation/pangea$ ls
CONTRIBUTING.md    config.js          index.js*          pangea.png
LICENSE            docs/              lib/               server-process.js
README.md          electron/          node_modules/      ui/
api/               http-server.js     package.json       ws-server.js
```

No app directory under electron/ either, in case that dir was just renamed.

```
~/bitnation/pangea/electron$ ls
index.js          menu.js           server-base.html  windows.js
```

**Comment by dominictarr** [comment]
you are cloning the wrong repo. use `git clone git@github.com:Bit-Nation/pangea-electron.git`

**Comment by dominictarr** [comment]
I think the instructions in the readme are misleading.

**Comment by andytudhope** [comment]
```
git clone git@github.com:Bit-Nation/pangea-electron.git
Cloning into 'pangea-electron'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dominictarr** [comment]
okay, your ssh is not set up right...
but you can do it over http instead
`git clone https://github.com/Bit-Nation/pangea-electron.git`

**Comment by dominictarr** [comment]
then do `npm run postinstall`

**Comment by dominictarr** [comment]
then `npm run release`

**Comment by andytudhope** [comment]
OK. Am doing this now. Can we update the installation documents? Especially the commands to get the latest version of patchwork? Should I not be running `npm install` first before the postinstall?

**Comment by dominictarr** [comment]
yes but I think you already ran that. Lets figure out what the right instructions are first.

**Comment by andytudhope** [comment]
OK, here is what worked for me (though not sure about how necessary the postinstall step was, seemed to give much the same output as `npm install`:

```
git clone https://github.com/Bit-Nation/pangea-electron.git
cd pangea-electron
npm install
npm run postinstall
npm run release
```

And then the usual Mac thing of double clicking the .dmg file, moving it across to the applications folder and opening it from there.

**Comment by dominictarr** [comment]
great!
can you upload the files it created to https://github.com/Bit-Nation/pangea-electron/releases/tag/2.12.6 ? (used "edit release" button)
@xstt you should be able to install those files then.

The weird thing is that there is an `./app/` folder which has it's own package.json and the postinstall script goes into that and runs install there too.

**Comment by dominictarr** [comment]
lets keep the issue open until we are 100% sure this is working, i.e. when it's installed on @xstt's laptop

**Comment by andytudhope** [comment]
I think that it is now? If not it's because the dmg isn't signed and she hasn't altered her security settings. I cannot sign the dmg with this computer and the developer account it has associated with it for reasons given in our slack. Perhaps someone else can follow my steps and sign it for us?

**Comment by andytudhope** [comment]
Also, have set up my ssh keys correctly now (there was some confusion over an old device) and also we should see if we can put these releases on git ssb (that shit is cool - thanks!)

**Comment by ETeissonniere** [comment]
Issue fixed, closing
