### ISSUE TITLE
Modular architecture

### ISSUE THREAD

**Issue by ETeissonniere** [Bit-Nation/pangea-electron#3]
Hey!

It would be nice if we can have an architecture running a "daemon" handling everything related to ssb and then a "client" interacting with the daemon and managing the GUI stuff.

**Comment by dominictarr** [comment]
that is basically how it works - scuttlebot is the server, and http://github.com/ssbc/ssb-client is the client, which is built into the UI.

**Comment by ETeissonniere** [comment]
Thanks :smile:
